# https://gethomepage.dev/
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: "homepage"
    restart: "unless-stopped"
    ports:
      - 8030:3000
    volumes:
      - .config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.tecronin.uk, homepage # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
networks:
  default:
    external: true
    name: share-net
